##---------------------------------------------------------------------------------------
# 网站配置
##---------------------------------------------------------------------------------------
site:
  icon: /medias/favicon.ico # 网站图标

  
##---------------------------------------------------------------------------------------
# 手机适配配置
##---------------------------------------------------------------------------------------

user: 
  pic: /medias/user.jpg # 用户图标
  description: 个人简介
  emil: "13396298960@163.com"

phoneSlide:
  menuWidth: 300     # 滑块的宽度 default：240
  position: left     # 滑动出现位置
  closeOnClick: true # 点击内部条目自动关闭滑块
  draggable: true    # 是否可以在屏幕边缘滑动出现
  userBackground: /medias/userbackground.jpg


##---------------------------------------------------------------------------------------
# header
##---------------------------------------------------------------------------------------
# nav
## 支持rgba透明设置
nav:
  color: ""

navLogo: # 支持文字和图片 同时存在显示图片
  image:
    enable: false
    url: 
  text:
    enable: true
    text: Barry
  
# menu
## icon 为 fontawesome框架
## 可以查找 http://fontawesome.dashgame.com/ 并设置 
menu:
  Index:
    url: / #String
    icon:  #String
  Archives:
    url: /categories/Android
    icon:
  About: 
    url: /about
    icon:
  FriendLink: 
    url: /
    icon:

# banner
## 有多个banner直接添加即可
## icon 为 fontawesome框架
## 可以查找 http://fontawesome.dashgame.com/ 并设置
indexBanner:
  btn:
    - icon: "qq"
      url: "https://github.com/JomBarry"
    - icon: "git"
      url: "https://github.com/JomBarry"
  banner:
    - url: /
      title: "BarryBlog"
      content: "wellcome !!!"
      image: "/medias/images/banner/background1.jpg"
    - url: /
      title: "BarryBlog"
      content: "wellcome !!!"
      image: "/medias/images/banner/background2.jpg"


##---------------------------------------------------------------------------------------
# 标题（一） showPostsTitle 值为空则不显示该栏目
##---------------------------------------------------------------------------------------
indexTitle1:
  enable: true
  icon: "font-awesome"
  text: "推荐文章"
  color: "000"
  lineColor: "fff"
  showPostsTitle: # 推荐文章时间 YYYY-MM-DD hh:mm:ss
    - "2019-07-01 18:55:11"
    - "2019-07-01 14:50:08"
    - 
    - 

##---------------------------------------------------------------------------------------
# 标题（二）
##---------------------------------------------------------------------------------------
## 按照 Categories 分类
## 输入文章类别相关设置 自动判断并设值样式
indexTitle2:
  showPostsNumber: 6 # 默认主页面显示文章数
  Android:
    icon: "android"
    text: "Android"
    color: "000"
    lineColor: "fff"
  Java:
    icon: "cubes"
    text: ""
    color: "000"
    lineColor: "fff"

##---------------------------------------------------------------------------------------
# about
##---------------------------------------------------------------------------------------
about: 
  background: 


##---------------------------------------------------------------------------------------
# floatingMenu 浮动菜单
##---------------------------------------------------------------------------------------
floatingMenu: 
  enable: true
  text: 分类
  url: /categories
  initFontColor: ""
  hoverFontColor: ""
  itemFontColor: ""
  itemhoverFontColor: "#000"
  itemHoverBackground: "green"
  Colourful: # 配置单个选项
    enable: true
    item: # 最多9个
      - icon: android
        url: 
        fontcolor: 
        background: 
        hoverFontColor: yellow
        hoverBackground: 
      - icon: 
        url: 
        fontcolor: 
        hoverFontColor: 
        hoverBackground:


##---------------------------------------------------------------------------------------
# 标签云
##---------------------------------------------------------------------------------------
# hexo-tag-cloud
tag_cloud:
    textFont: Trebuchet MS, Helvetica
    textColor: '#333'
    textHeight: 25
    outlineColor: '#E2E1D1'
    maxSpeed: 0.5

##---------------------------------------------------------------------------------------
# 分类页面设置 Categories
##---------------------------------------------------------------------------------------
categories:
  banner:
    - "/medias/images/postBanner/background1.jpg"
    - "/medias/images/postBanner/background2.jpg"
    - "/medias/images/postBanner/background3.jpg"
    - "/medias/images/postBanner/background4.jpg"



##---------------------------------------------------------------------------------------
# 文章设置 Posts
##---------------------------------------------------------------------------------------
# 默认
posts: 
  defaultThumbnail: # 默认缩略图
    - /medias/images/postDemo/demo1.jpg
    - /medias/images/postDemo/demo2.jpg
    - /medias/images/postDemo/demo3.jpg
  dateFormat: YYYY-MM-DD # 日期格式 时间显示24制（H:mm:ss）12制（hh:mm:ss）
  defaultBanner: # postBanner轮播图 若在post内部设置 在markdown文档上部添加 banner：[] 属性
    - "/medias/images/postBanner/background1.jpg"
    - "/medias/images/postBanner/background2.jpg"
    - "/medias/images/postBanner/background3.jpg"
    - "/medias/images/postBanner/background4.jpg"

tocbot:
  tocSelector: '.js-toc'
  contentSelector: "#post-content"
  scrollSmooth: true
  headingSelector: h1, h2, h3, h4, h5
  headingsOffset: 45
  scrollSmoothOffset: -45

# 按分类给定class样式tag也会有同样的颜色(注意大小写)
categoriesColor: 
  Android: grad_purple_red
  Java: grad_Cambridge_blue
  Hexo: grad_blue_darkBlue

tagsColor: # 设置了tag优先使用（注意大小写）
  Android: grad_red_purple
  Hexo: grad_purple_blue
##---------------------------------------------------------------------------------------
# 友情链接
##---------------------------------------------------------------------------------------
FriendLink: 
    百度: 
      url: www.baidu.com
      icon: 
    搜狗: 
      url: www.sogou.com
      icon: 



##----------------------------------------------------------------------------------------
## 资源文件
##----------------------------------------------------------------------------------------
libs:
  medias:
  materialize:
    js: /libs/materialize/js/materialize.min.js
    css: /libs/materialize/css/materialize.min.css
  jQuery:
    js: /libs/jquery/jquery-3.4.1.min.js
  fontAwesome: 
    css: /libs/fontAwesome/css/font-awesome.min.css
  tocbot: 
    js: /libs/tocbot/tocbot.min.js
    css: /libs/tocbot/tocbot.css
  lightgallery: 
    js: 
      lightgallery: /libs/lightgallery/js/lightgallery.min.js
      thumbnail: /libs/lightgallery/js/lg-thumbnail.min.js
      fullscreen: /libs/lightgallery/js/lg-fullscreen.min.js
    css: /libs/lightgallery/css/lightgallery.css
  echarts:
    echarts: /libs/echarts/echarts.min.js
    echartsGl: /libs/echarts/echarts-gl.min.js
    ecStat: /libs/echarts/ecStat.min.js
    dataTool: /libs/echarts/dataTool.min.js
    china: /libs/echarts/china.js
    world: /libs/echarts/world.js
    api: /libs/echarts/api.js
    bmap: /libs/echarts/bmap.min.js
    simplex: /libs/echarts/simplex.js
    theme: /libs/echarts/shine.js
  aboutHistroy:
    css: /libs/aboutHistroy/css/public.css
    js: /libs/aboutHistroy/js/flexslider.js



##----------------------------------------------------------------------------------------
## 配置文件
##----------------------------------------------------------------------------------------
commonPage:
  js:
  css: 
    browserScrollBar: /css/common/browserScrollBar.css
    gradientRamp: /css/common/gradientRamp.css
partial:
  css: 
    index_banner: /css/partial/index_banner.css
    index_header: /css/partial/index_header.css
    categroies_banner_common: /css/partial/categroies_banner_common.css
    post_banner_common: /css/partial/post_banner_common.css
  js: 
indexPage:
  js:
    header: /js/index/header.js
    main: /js/index/main.js
    test: /js/test.js
  css:
    main: /css/index/main.css
postPage:
  js:
    commonBanner: /js/post/postBannerCommon.js
    main: /js/post/main.js
    mainCss: /js/post/main_css.js
  css:
    post: /css/post/post.css
    main: /css/post/main.css
categoriesPage: 
  js:
    main: /js/categories/main.js
  css:
    button: /css/categories/button.css
    main: /css/categories/main.css
categoryPage:
  js:
  css:
    main: /css/category/main.css
tagPags:
  css:
    main: /css/tag/main.css
  js:
aboutPage:
  js:
    main: /js/about/main.js
    aboutHistroy: /js/about/aboutHistroy.js
